# cloudbuild-pr.yaml - Pull request validation
# This configuration runs on pull requests to validate changes without applying

steps:
  # Step 1: Validate Terraform syntax
  - name: 'hashicorp/terraform:1.5'
    id: 'terraform-validate'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Validating Terraform configuration..."
        terraform fmt -check=true -diff=true
        terraform init -backend=false
        terraform validate
    env:
      - 'TF_IN_AUTOMATION=true'

  # Step 2: Terraform Plan (show changes without applying)
  - name: 'hashicorp/terraform:1.5'
    id: 'terraform-plan'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Planning Terraform changes for PR review..."

        # Initialize with backend
        terraform init

        # Plan the configuration
        echo "=== Planning Terraform configuration ==="
        # Use -var-file only if terraform.tfvars exists
        if [ -f terraform.tfvars ]; then
          terraform plan -var-file=terraform.tfvars
        else
          terraform plan
        fi

        echo "=== PR validation completed ==="
        echo "Review the plan above before merging to main"
    env:
      - 'TF_IN_AUTOMATION=true'
      - 'GITHUB_TOKEN=${_GITHUB_TOKEN}'
      - 'TF_VAR_github_token=${_GITHUB_TOKEN}'
      - 'TF_VAR_github_owner=${_GITHUB_OWNER}'
      - 'TF_VAR_gcp_project_id=${PROJECT_ID}'

# Use same substitutions and service account
substitutions:
  _GITHUB_TOKEN: 'projects/${PROJECT_ID}/secrets/github-token/versions/latest'
  _GITHUB_OWNER: 'dg-ghtest'

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/terraform-automation@${PROJECT_ID}.iam.gserviceaccount.com'

options:
  machineType: 'E2_STANDARD_2'
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'